### ISSUE TITLE
API missing method to walk through providers

### ISSUE THREAD

**Issue by jonathansp** [terraform-linters/tflint-plugin-sdk#118]
Given the following _providers.tf_ file:

```hcl
provider "azuread" {
    tenant_id = "00000000-0000-0000-0000-000000000000"
}

provider "databricks" {
}
```

I'm working on a tflint plugin to validate the requirements in our declared providers. I can see the providers were parsed correctly but there are no public methods to expose them.

<img width="676" alt="Screenshot 2021-05-20 at 13 30 05" src="https://user-images.githubusercontent.com/457972/118978733-8e9b8f80-b96f-11eb-8250-c0f19c5e6830.png">

Is there any way to walk through providers in order to validate their attributes?

**Comment by wata727** [comment]
You can get attributes/blocks from `hcl.Body` with `PartialContent` etc.
https://github.com/terraform-linters/tflint-ruleset-template/blob/e89e98658d51395a77e92405448cc376919fc8e8/rules/aws_s3_bucket_example_lifecycle_rule.go#L43-L50
https://github.com/hashicorp/hcl/blob/v2.10.0/structure.go#L35-L74

Also, if you want to access a structure like providers, you can use the `Config` API to access the `Provider`.
https://pkg.go.dev/github.com/terraform-linters/tflint-plugin-sdk@v0.8.2/tflint#Runner
https://pkg.go.dev/github.com/terraform-linters/tflint-plugin-sdk@v0.8.2/terraform/configs#Provider

**Comment by jonathansp** [comment]
Thanks for replying @wata727 

I guess the issue here is that `tflint.Runner` interface does not provide any public method to list data from providers. 



```go

 ... Check(runner tflint.Runner) error { ... 

config, _ := runner.Config()

call len(config.Module.ProviderMetas)
0
call len(config.Module.ProviderLocalNames)
0
call len(config.Module.ProviderConfigs)
0
```

The test case for this is:

```go
func Test_DummyTestCase(t *testing.T) {
	cases := []struct {
		Name     string
		Content  string
		Expected helper.Issues
	}{
		{
			Name: "dummy test case",
			Content: `
provider "azuread" {
	tenant_id = "00000000-0000-0000-0000-000000000000"
}
provider "databricks" {}`,
			Expected: helper.Issues{
				{
					Rule: NewDummyRule(),
					Range: hcl.Range{
						Filename: "providers.tf",
						Start:    hcl.Pos{Line: 3, Column: 21},
						End:      hcl.Pos{Line: 3, Column: 31},
					},
				},
			},
		},
	}
	rule := NewDummyRule()
	for _, tc := range cases {
		runner := helper.TestRunner(t, map[string]string{"providers.tf": tc.Content})
		if err := rule.Check(runner); err != nil {
			t.Fatalf("Unexpected error occurred: %s", err)
		}
		helper.AssertIssues(t, tc.Expected, runner.Issues)
	}
}

```

What is not clear to me is, how should I access these providers inside the Check() method.

```go
// Check checks whether ...
func (r *DummyRule) Check(runner tflint.Runner) error {

	... 


	return runner.EmitIssue(
		r,
		fmt.Sprintf("issue"),
		hcl.Range{},
	)
}
```

Thanks once again.

**Comment by wata727** [comment]
Ah, understood. This is a `helper.TestRunner` issue. The runner provided by tflint-plugin-sdk is different from the real Runner and does not support some features. For instance, provider is not supported:

https://github.com/terraform-linters/tflint-plugin-sdk/blob/18655e360fe1cfa6a06c7abf91a1ac0a2df0df6b/helper/runner.go#L298-L299

The issue is mentioned in https://github.com/terraform-linters/tflint-plugin-sdk/issues/64. There should be no problem in the real use case.

**Comment by wata727** [comment]
I think it is difficult to add a workaround for the fake runner because the `Runner` interface doesn't have the `Files()` method. The only workaround is to add an implementation that decodes the `provider` to the fake runner.

**Comment by jonathansp** [comment]
Hi @wata727 I may have misunderstood what you have explained. [Runner interface is part of tflint-plugin-sdk](https://github.com/terraform-linters/tflint-plugin-sdk/blob/18655e360fe1cfa6a06c7abf91a1ac0a2df0df6b/tflint/interface.go#L33), (_not from tflint or terraform_) and this interface [does not implement all the public methods from the original Runner struct](https://github.com/terraform-linters/tflint/blob/master/tflint/runner.go#L218).  Runner interface must have implemented _Files()_ method (an all the public ones) in order to mimic the expected behavior, even if these methods just raise an error when not supported yet.    Some of them are:

```go
func (r *Runner) TFConfigPath() string 
func (r *Runner) LookupIssues(files ...string) Issues
func (r *Runner) Files() map[string]*hcl.File
```

Can you please confirm if my understanding is correct? Or I'm confused due the name _Runner_ 😅  

Many thanks

**Comment by wata727** [comment]
> Runner interface is part of tflint-plugin-sdk, (not from tflint or terraform) and this interface does not implement all the public methods from the original Runner struct.

Correct. To be precise, this interface is not related to the tflint's Runner struct.

Originally, all rules were designed to take [a Runner struct](https://github.com/terraform-linters/tflint/blob/a50db0dbaf8f38a1d4ee3a2ef1ad9cff15dccd3e/tflint/runner.go#L20-L33) as an argument, but we needed to abstract implementation to support the plugin system. That is [the Runner interface](https://github.com/terraform-linters/tflint-plugin-sdk/blob/18655e360fe1cfa6a06c7abf91a1ac0a2df0df6b/tflint/interface.go#L33).

In the plugin system, the implementation that satisfies the Runner interface is [an RPC client](https://github.com/terraform-linters/tflint-plugin-sdk/blob/18655e360fe1cfa6a06c7abf91a1ac0a2df0df6b/tflint/client/client.go#L18-L21), not the Runner struct. This is because we cannot decode complex structures over RPC. The RPC client makes a request to tflint's host process server. The server process returns the result to the RPC client using the Runner struct. See also [Architecture](https://github.com/terraform-linters/tflint-plugin-sdk#architecture).

For testing, it's difficult to have an RPC client, so we provide a fake Runner.

> Runner interface must have implemented Files() method (and all the public ones) in order to mimic the expected behavior

No, as mentioned above, [tflint's Runner struct](https://github.com/terraform-linters/tflint/blob/a50db0dbaf8f38a1d4ee3a2ef1ad9cff15dccd3e/tflint/runner.go#L20-L33) and [the Runner interface](https://github.com/terraform-linters/tflint-plugin-sdk/blob/18655e360fe1cfa6a06c7abf91a1ac0a2df0df6b/tflint/interface.go#L33) are irrelevant, and the Files() method is the logic of the Runner struct, so the interface doesn't need to implement this.

I'm also worried about the complexity of this architecture... 😖 
In the future, tflint's Runner struct will be a more server-specific implementation (now, [some built-in rules use the Runner directly](https://github.com/terraform-linters/tflint/blob/a50db0dbaf8f38a1d4ee3a2ef1ad9cff15dccd3e/rules/terraformrules/terraform_comment_syntax.go#L42)) and maybe improved.

**Comment by jonathansp** [comment]
Many thanks for digging into, @wata727. Now I got it. Would be correct, based on the `RootProvider(name)` function, extending tflint, adding a `Providers()` function, as the following snippet:

```go
// Providers returns the providers configuration on the module as tfplugin.Provider
func (s *Server) Providers(req *tfplugin.ProvidersRequest, resp *tfplugin.ProvidersResponse) error {
	var providers []*tfplugin.Provider

	for _, provider := range s.rootRunner.TFConfig.Module.ProviderConfigs {
		providers = append(providers, s.encodeProvider(provider))
	}

	for _, provider := range s.runner.TFConfig.Module.ProviderConfigs {
		providers = append(providers, s.encodeProvider(provider))
	}

	*resp = tfplugin.ProvidersResponse{
		Providers: providers,
	}
	return nil
}
```

If not, do you think we currently have any other alternative to listing the providers?

**Comment by wata727** [comment]
You can get providers as follows by using Config() API. However, as mentioned above, you cannot get providers in tests.

```go
import "github.com/terraform-linters/tflint-plugin-sdk/tflint"

...

func (r *ExampleRule) Check(runner tflint.Runner) error {
	runner.Config().Module. ProviderConfigs // => map[string]*Provider
}
```

Adding an API like Providers() seems like a good idea. If you are interested, I'm happy to review it.

**Comment by wata727** [comment]
TFLint v0.30 / Plugin SDK v0.9 has been released.
