### ISSUE TITLE
Provide access to module name on runner

### ISSUE THREAD

**Issue by anurodh-ti** [terraform-linters/tflint-plugin-sdk#165]
Can we get present modules information while parsing through the terraform code through tflint?
We need to find for each resource in which module that resource is made because same resource name can be present in different modules.

**Comment by sabhya-ti** [comment]
Thank you for taking the time to reach out Ben. The plugin that I am hoping to develop--the conditions that it is going to use to emit issues differs from resource to resource. 
For example: module.server-1.showcase-1 should emit an issue when the instance_type is not "t2.micro", but module.server-2.showcase-1 should emit an issue when the instance type is not "t2.large".
I need a way to uniquely identify the resource blocks. Using just the terraform reference name ("showcase-1") in this case does not suffice as it is not unique across all modules, it is only unique across the module. However, server-1.showcase-1 and server-2.showcase-1 is unique. But there is no way that I have been able to find that lets me associate server-1 (the terraform reference name for that module) or server-2 with the resource blocks present in their modules. If I'm able to do that, my job would be done. 
Thank you again for writing back.

**Comment by bendrucker** [comment]
Per the above explanation, this is already handled. You emit issues on an expression containing a variable in the module, TFLint automatically associates them with the attribute in the calling `module`. 

To continue this discussion I need to hear why the existing functionality is insufficient rather than why your naive solution seems right to you.

**Comment by bendrucker** [comment]
This still isn't making sense to me as a whole. 

How is the address of an object going to get a deployed resource? Are you going into Terraform state and digging it out?

What you're describing, ie validating the state of the underlying resource after creation, is well outside the normal bounds of a linter.

Since the request is reasonable in the abstract we'd review PRs but given the lack of clear general case for this for plugin development it's not something I'd anticipate working on directly. Happy to continue discussion.

**Comment by wata727** [comment]
Ben, thank you for clarifying the issue. Certainly what they are trying to do may be too difficult for linter. However, this request to be able to get the name of the parent module from a child module seems to make sense.

Perhaps it's better to provide a method like `runner.Path()`. This is a feature that already exists in runners that are not via plugins, and you can get the module path as follows:
https://github.com/terraform-linters/tflint/blob/a21bdd79b0ff845744b72bb2915f1a6d16adfdfd/tflint/runner_test.go#L182

However, I'm still interested in whether this will meet their demands.

**Comment by sabhya-ti** [comment]
Thank you again for taking the time to write back to understand more deeply what we are trying to do.

Responding to Ben first, yes. Our current line of thinking does involve going through the Terraform state file and digging out the information that we need from there. And yes, we acknowledge that validating the state like this is indeed out of the bounds of a traditional linter and we would be pushing the boundaries of what a linter is supposed to do.

As for Kazuma's query, assuming that "module1" refers to the terraform reference name for the module, 

i.e. the module was declared as

module "module1"{
source = ""
} 

in the root module, 

then getting that available to us via the runner as we are inspecting the resources of that module should indeed solve our requirements, yes. We can get the reference name for the resources already via the getModuleContent() function of the runner interface as we are inspecting a resource block. If we are able to get the module name as well, together both of them should be enough to ensure uniqueness across the entire terraform template codebase in the project.

Looking forward to hearing back.

**Comment by wata727** [comment]
Understood. Inspection based on the Terraform state is not recommended as it greatly complicates your rules, but you should be able to identify unique resources from the state by using `runner.Path ()`.
