### ISSUE TITLE
Question: how to get root module absolute path

### ISSUE THREAD

**Issue by Vince-Chenal** [terraform-linters/tflint-plugin-sdk#218]
Hey,

In order to enforce terraform folders location (for example .infra at the root of git repo), I'd like to be able to get the root module absolute path. I can't find another solution than getting the current workdir (which can be wrong if tflint is executed from another directory).
There's the `GetFiles()` function but it only give the filenames.

Is there another way?

**Comment by wata727** [comment]
Unfortunately there doesn't seem to be a good way to do it.
Getting the current directory is probably the best way. The filename retrieved by `GetFiles()` is the relative path of the current directory, so you may be able to use it. However, this is not the spec and is subject to change in the near future, so I wouldn't recommend it unless absolutely necessary.

I'm not sure how it should be, but I have some ideas in mind:

- Makes the filename retrieved by `GetFiles()` an absolute path.
  - It eliminates ambiguity due to dependencies on the current directory. It is also good for the [recursive inspection](https://github.com/terraform-linters/tflint/issues/1355) planned in the future.
- `GetModulePath()` not only returns the path of the module tree, but also the absolute path on filesystem.

**Comment by Vince-Chenal** [comment]
Thanks for your answer
Ok I guess I'll go with current directory for now and follow sdk evolution :+1:

**Comment by wata727** [comment]
SDK v0.15 introduces `runner.GetOriginalwd()`. Better to use this than `os.Getwd()`.

**Comment by Vince-Chenal** [comment]
Oh nice did not see this one, thank you :pray:
